@startuml

title Verteilungsdiagramm

node "3D Drucker" {
  [Empfang]
  [Drucken]
  [Status + Versand]

}
node "Cameras" {
  [Erfassung]
  [Videodaten]
  [Versenden]

}
node "Sicherheit-Einheit" {
  [Sensoren]
  [Alarm]
  [Notstop]
  [Monitoring]
  [Sicherheitsdaten]
}


node "Zentraler Druckserver" {
  [Versenden]
  [Auswahl]
  [Steuern]
  [Empfang]
  [Druckerdatenbank]
  [Druckauftragswarteschlange]
  [Netzwerk-Modul-A]-->[Netzwerk-Client-A]
}


node "Zentraler Verwaltungsserver"{
  [Druckaufträge]
  [Web-Modul]-->[Web-Client]
  [Netzwerk-Modul-B]-->[Netzwerk-Client-B]
}
node "Web-Client" {

}
node "Mobil-Client Admin" {

}
node "Netzwerk-Client-A" {

}
node "Netzwerk-Client-B" {

}

@enduml