@startuml

title Klassendiagramm 3D-Drucker-Pool

class Printer {
  - id : int
  - label : String
  - profileId : int
  - producerId: int

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void
  + getProfileId() : int
  + setProfileId(int i) : void
  + getProducerId() : int
  + setProducerId(int i) : void

}

class PinterProfile {
  - id : int
  - x_size : int
  - y_size : int
  - z_size : int
  - name : String
  - printbed_type
  - printbed_heatable : boolean
  - extrudor =
  - filament_color

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void
  + getName() : String
  + setName(String n) : void

}


class PrintJob {
  - id : int
  - description : String
  - printerID : int
  - PRINTOBJEKT

  + getId() : int
  + setId(int i) : void
  + getDescription() : String
  + setDescription(String n) : void

}

class PrintJobQueue {

}

class PrinterProducer {
  - id : int
  - name : String
  - description : String
  - specialFeatures : String

  + getId() : int
  + setId(int i) : void
  + getName() : String
  + setName(String s) : void
  + getDescription() : String
  + setDescription(String s) : void
  + getSpecialFeatures() : String
  + setSpecialFeatures(String s) : void

}

class PrintJobVideoPicture {
  - id : int
  - fileName : String
  - timeStamp : date
  - description : String

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String s) : void
  + getFileName() : String
  + setFileName(String s) : void
  + getTimeStamp() : date
  + setTimeStamp() : void
  + getDescription() : String
  + setDescription(String s) : void

}
class PrintBed {
  - id : int
  - status : int
  - type : String

  + getId() : int
  + setId(int i) : void
  + getStatus() : String
  + setStatus(String s) : void
  + getType() : String
  + setType(String s) : void

}

class PrinterManager {
  - id : int

  + getId() : int
  + setId(int i) : void

}





class Camera {
  - id : int
  - name : String

  + getId() : int
  + setId(int i) : void
  + getName() : String
  + setName(String n) : void
}


class RoboticArm {
  - id : int
  - label : String
  - status : String

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void
  + getStatus() : String
  + setStatus(String l) : void
  + doJob(RoboticArmJob r): String

}
class RoboticArmJob {
  - id : int
  - label : String

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void
  + doJob(RoboticArmJob r): String

}

class RoboticArmManager {

  + startRoboticArmJob() :
  + checkStatus() :

}

class Sensor {
  - id : int
  - label : String
  - status

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void


}


class Alarm {
  - id : int
  - typ : String

  + getId() : int
  + setId(int i) : void
  + getTyp() : String
  + setTyp(String a) : void


}

class EmergencyStop {

  + stopPrintJob(int id) : String
  + stopAllPrintJobs() : String

}

class User {
  - id : int
  - email : String
  - username : String
  - password : String
  - activated : boolean
  - isAdmin : boolean

  + getId() : int
  + setId(int i) : void
  + getEmail() : String
  + setEmail(String e) : void
  + getUsername() : String
  + setUsername(String u) : void
  + getPassword() : String
  + setPassword(String pw) : void
  + getActivated() : boolean
  + setActivated(boolean act) : void
  + getIsAdmin() : boolean
  - setIsAdmin(boolean act) : void
  + activate() : void
  + register() : void
  + login() : void
}


@enduml

