@startuml

title Klassendiagramm 3D-Drucker-Pool

class Printer {
  - id : int
  - label : String
  - profileId : int

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void
  + getProfileId() : int
  + setprofileId(int i) : void

}

class PinterProfile {
  - id : int
  - label : String
  - name : String

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void
  + getName() : String
  + setName(String n) : void

}


class PrintJob {
  - id : int
  - name : String

  + getId() : int
  + setId(int i) : void
  + getName() : String
  + setName(String n) : void

}

class PrintJobQueue {
  - id : int

  + getId() : int
  + setId(int i) : void

}

class PrinterProducer {
  - id : int
  - name : String

  + getId() : int
  + setId(int i) : void
  + getName() : String
  + setName(String n) : void

}

class PrintJobVideo {
  - id : int
  - fileName : String

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void
  + getFileName() : String
  + setFileName(String n) : void

}

class PrintJobPicture {
  - id : int
  - fileName : String

  + getId() : int
  + setId(int i) : void
  + getFileName() : String
  + setFileName(String n) : void

}

class PrinterManager {
  - id : int


  + getId() : int
  + setId(int i) : void

}


class User {
  - id : int
  - firstName : String
  - lastName : String
  - email : String
  - username : String
  - password : String
  - activated : boolean
  - isAdmin : boolean

  + getId() : int
  + setId(int i) : void
  + getFirstName() : String
  + setFirstName(String fn) : void
  + getLastName() : String
  + setLastName(String ln) : void
  + getEmail() : String
  + setEmail(String e) : void
  + getUsername() : String
  + setUsername(String u) : void
  + getPassword() : String
  + setPassword(String pw) : void
  + getActivated() : boolean
  + setActivated(boolean act) : void
  + getIsAdmin() : boolean
  - setIsAdmin(boolean act) : void
  + activate() : void
  + register() : void
  + login() : void
}


class Camera {
  - id : int
  - name : String

  + getId() : int
  + setId(int i) : void
  + getName() : String
  + setName(String n) : void
}


class RoboticArm {
  - id : int
  - label : String
  - status . String

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void
  + getStatus() : String
  + setStatus(String l) : void
  + doJob(RoboticArmJob r): String

}
class RoboticArmJob {
  - id : int
  - label : String

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void
  + doJob(RoboticArmJob r): String

}

class RoboticArmManager {

  + startRoboticArmJob() :
  + checkStatus() :

}

class Sensor {
  - id : int
  - label : String
  - status

  + getId() : int
  + setId(int i) : void
  + getLabel() : String
  + setLabel(String l) : void


}

class PrintBed {
  - id : int
  - status : int

  + getId() : int
  + setId(int i) : void
  + getStatus() : String
  + setStatus(String l) : void

}

class Alarm {
  - id : int
  - typ : String

  + getId() : int
  + setId(int i) : void
  + getTyp() : String
  + setTyp(String a) : void


}

class EmergencyStop {

  + stopPrintJob(int id) : String
  + stopAllPrintJobs() : String

}




@enduml

